### ISSUE TITLE
 error: 'Levine_32dim_SE' not found in ExperimentHub

### ISSUE THREAD

**Issue by 93161** [lmweber/HDCytoData#6]
Dear Authors,
when  I install HDCytoData,  I get the following error:

>* installing *source* package 'HDCytoData' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded from temporary location
Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Using 'localHub=TRUE'
  If offline, please also see BiocManager vignette section on offline use
Error: package or namespace load failed for 'HDCytoData':
 .onLoad failed in loadNamespace() for 'HDCytoData', details:
  call: FUN(X[[i]], ...)
  error: 'Levine_32dim_SE' not found in ExperimentHub
Error: loading failed
Execution halted
ERROR: loading failed

Has anyone come across this issue before? Is there anything I can do to get this to work?

Thank you! 
Shan

**Comment by xiaozhangPrivate** [comment]
I'm having the same problem...

**Comment by lmweber** [comment]
Thanks for the messages. I tried installing the package and loading the data with the `Levine_32dim_SE()` function just now, and it worked for me.

Is this working for you now? Maybe there was a temporary glitch with the Bioconductor install system last week.

If not, could you please let me know your R and Bioconductor versions? (`BiocManager::version()` for the Bioconductor version)

**Comment by xiaozhangPrivate** [comment]
I've just tried it again. It's working now. 
Maybe there is something wrong with the connection (when I use a VPN, everything is solved -_-). 
Thanks a lot!

**Comment by lmweber** [comment]
Great, thanks for letting me know.

I'll close the issue -- let me know if there are any further problems.
